import { existsSync, readFileSync } from 'node:fs';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface CreateCommandOptions {
  force?: boolean;
  verbose?: boolean;
}

export async function runCreateCommand(
  projectName: string,
  options: CreateCommandOptions = {},
): Promise<void> {
  const normalizedProjectName = projectName.trim();
  if (!normalizedProjectName) {
    throw new Error('Project name is required. Usage: create-clawkit my-agent');
  }

  if (!/^[a-zA-Z0-9._-]+$/.test(normalizedProjectName)) {
    throw new Error('Project name may contain only letters, numbers, dot, underscore, and hyphen.');
  }

  const targetDir = resolve(process.cwd(), normalizedProjectName);
  const alreadyExists = existsSync(targetDir);

  if (alreadyExists) {
    const existingItems = await readdir(targetDir);
    if (existingItems.length > 0 && !options.force) {
      throw new Error(
        `Target directory is not empty: ${targetDir}\nUse --force to overwrite scaffold files.`,
      );
    }
  }

  await mkdir(targetDir, { recursive: true });
  await mkdir(resolve(targetDir, 'logs'), { recursive: true });
  await mkdir(resolve(targetDir, 'memory'), { recursive: true });
  await mkdir(resolve(targetDir, 'security'), { recursive: true });

  const packageName = toPackageName(normalizedProjectName);
  const files: Record<string, string> = {
    'agent.ts': renderAgentConfig(normalizedProjectName),
    'README.md': renderProjectReadme(normalizedProjectName),
    'package.json': renderProjectPackageJson(packageName),
    'security/graylist.json': loadDefaultGraylist(),
    '.gitignore': ['node_modules', '.DS_Store', 'memory/*.db', 'logs/*.jsonl', '.clawkit-cache'].join(
      '\n',
    ),
    'logs/.gitkeep': '',
    'memory/.gitkeep': '',
  };

  await Promise.all(
    Object.entries(files).map(async ([relativePath, content]) => {
      const destination = resolve(targetDir, relativePath);
      await writeFile(destination, content, 'utf8');
    }),
  );

  if (options.verbose) {
    console.log(`Scaffold files written to ${targetDir}`);
  }

  console.log(`\nCreated ClawKit project: ${basename(targetDir)}`);
  console.log(`Path: ${targetDir}`);
  console.log('\nNext steps:');
  console.log(`1. cd ${basename(targetDir)}`);
  console.log('2. npx clawkit dev --verbose');
}

function renderAgentConfig(projectName: string): string {
  return `const agent = {
  name: '${projectName}',
  instructions: 'You are a helpful AI agent built with ClawKit.',
  memory: {
    dbPath: './memory/memory.db',
    dimensions: 128,
  },
  search: {
    enabled: true,
    allowGray: true,
    maxResults: 5,
    graylistPath: './security/graylist.json',
  },
};

export default agent;
`;
}

function renderProjectReadme(projectName: string): string {
  return `# ${projectName}

Agent project generated by ClawKit.

## Run

\`\`\`bash
npx clawkit dev --verbose
\`\`\`

## Config

Edit \`agent.ts\` and save. The dev runtime hot-reloads config changes automatically.

## Commands in dev shell

- \`/search <query>\` - web search with domain graylist checks
- \`/remember <text>\` - store memory locally in SQLite
- \`/recall <query>\` - semantic memory lookup
- \`/help\` - command reference
- \`/exit\` - exit shell
`;
}

function renderProjectPackageJson(packageName: string): string {
  return JSON.stringify(
    {
      name: packageName,
      private: true,
      type: 'module',
      scripts: {
        dev: 'npx clawkit dev',
        'dev:verbose': 'npx clawkit dev --verbose',
      },
    },
    null,
    2,
  );
}

function toPackageName(projectName: string): string {
  return projectName
    .toLowerCase()
    .replace(/[^a-z0-9._-]/g, '-')
    .replace(/^[._-]+/, '')
    .replace(/[._-]+$/, '') || 'clawkit-agent';
}

function loadDefaultGraylist(): string {
  const candidates = [
    resolve(process.cwd(), 'src/security/graylist.json'),
    resolve(dirname(fileURLToPath(import.meta.url)), '../security/graylist.json'),
  ];

  for (const candidate of candidates) {
    if (!existsSync(candidate)) {
      continue;
    }

    try {
      return readFileSync(candidate, 'utf8');
    } catch {
      continue;
    }
  }

  return JSON.stringify(
    {
      green: ['openai.com', 'github.com', 'nodejs.org', 'developer.mozilla.org', 'wikipedia.org'],
      gray: ['reddit.com', 'medium.com', 'substack.com', 'quora.com'],
      red: ['example-malware.com', 'example-phishing.com', 'malware.test', 'phishing.test'],
    },
    null,
    2,
  );
}
